version: "3.8"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MQTT_BROKER=tcp://broker:1883
      - MQTT_USER=cntrl
      - MQTT_PASS=
    volumes:
      - ./static/uploads:/app/static/uploads
    restart: unless-stopped
    depends_on:
      - broker

  broker:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped
